version: '3.4'

services:
  cataloguedb:
    image: mongo

  basketdb:
    image: redis:alpine

  discountdb:
    image: postgres
  
  portainer:
    image: portainer/portainer-ce
  
  pgadmin:
    image: dpage/pgadmin4

  catalogue.api:
    image: ${DOCKER_REGISTRY-}catalogueapi
    build:
      context: .
      dockerfile: Services/Catalogue/Catalogue.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGw/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:
